AStages.addRestrictionForItem("astages/stage3/items/core", "stage_3",
    "tconstruct:hepatizon_ingot",
    "tconstruct:ender_slime_vine",
    "tinkerscalibration:soulgold_ingot",
    "tinkers_thinking:soul_vine",
    "mysticalagriculture:imperium_ingot",
    "tinkers_advanced:blitz_lumium",
    "sakuratinker:eezo_ingot",
    "tinkers_advanced:osgloglas_ingot",
    "tinkers_advanced:bismuth_ingot",
    "tinkers_things:hematite",
    "sakuratinker:nihilite_ingot",
    "tinkerscalibration:oraclium_ingot",
    "sakuratinker:mycelium_slimesteel",
    "tinkers_thinking:warden_steel_ingot",
    "tinkerscalibration:lindsteel_ingot",
    "tconstruct:queens_slime_ingot",
    "sakuratinker:bear_interest_ingot",
    "cloudertinker:glaze_ingot",
    "tinkerscalibration:mandite_ingot",
    "tinkers_advanced:blaze_netherite",
    "tinkerscalibration:fazelle_ingot",
    "tinkers_advanced:penumatic_reinforced_steel",
    "tconstruct:blazing_bone",
    "tinkerscalibration:breashell",
    "tinkers_advanced:blizz_enderium",
    "tinkers_thinking:bound_chain",
    "projecte:dark_matter",
    "mekanism:ingot_refined_obsidian",
    "sakuratinker:prometheum_ingot",
    "sakuratinker:frost_slimesteel",
    "cloudertinker:forest_gem",
    "sakuratinker:cold_iron_alloy",
    "sakuratinker:aurumos",
    "sakuratinker:arcane_alloy",
    "twilightforest:castle_brick",
    "sakuratinker:terracryst",
    "minecraft:netherite_ingot",
    "deep_aether:stratus_ingot",
    "tconstruct:cinderslime_ingot",
    "tinkerscalibration:witherium_ingot",
    "cloudertinker:hydra_scale",
    "cloudertinker:steelbone",
    "tinkers_delight:tasty_bone",
    "sakuratinker:echo_slimesteel",
    "tinkerscalibration:emperorslime_ingot",
    "mushroom_daydream:sjngp",
    "tconstruct:foundry_controller",
    "tconstruct:smeltery_controller",
    "avaritia:nether_crafting_table"
)

AStages.addRestrictionForTag("astages/stage3/tags/combat_maid", "stage_3", "marveloustinker:combat_maid")
AStages.addRestrictionForTag("astages/stage3/tags/seram_slashblade", "stage_3", "ticex:seram/slashblade")

AStages.addRestrictionForModRecipe("astages/stage3/recipes/mods/draconicevolution", "stage_3", "draconicevolution");
AStages.addRestrictionForModRecipe("astages/stage3/recipes/mods/mekanism", "stage_3", "mekanism");