AStages.addRestrictionForItem("astages/stage4/items/core", "stage_4",
    "avaritia:end_crafting_table"
)

AStages.addRestrictionForTag("astages/stage4/tags/stage_4", "stage_4", "wqjy:stage_4")

AStages.addRestrictionForModRecipe("astages/stage4/recipes/mods/draconicevolution", "stage_4", "draconicevolution");

RecipeMachineStage.addRecipes('tconstruct:melting', [
    'aether_tinker:materials/warding/knightslime_melting',
    'aether_tinker:materials/warding/knightslime_materials_melting',
    'tinkers_advanced:materials/antimatter/antimatter_melting_250mb',
    'tinkers_advanced:materials/antimatter/antimatter_material_melt',
    'mushroom_daydream:materials/dark_thing/dark_thing',
    'mushroom_daydream:materials/dark_thing/dark_thing_melting',
    'mushroom_daydream:materials/dark_thing/dark_thing_materials_melting',
    'mushroom_concept:materials/almighty/knightslime_melting',
    'mushroom_concept:materials/almighty/knightslime_materials_melting',
    'mushroom_concept:materials/xuan/knightslime_melting',
    'mushroom_concept:materials/xuan/knightslime_materials_melting',
    'tinkerscalibration:tools/materials/melting/redmatter/block',
    'tinkerscalibration:tools/materials/melting/redmatter/redmatter',
    'tinkerscalibration:tools/materials/melting/redmatter/part',
    'sakuratinker:materials/gluttonous/gluttonous_melting_ingot',
    'sakuratinker:materials/gluttonous/gluttonous_material_melt',
    'sakuratinker:materials/two_form_mist_star/two_form_mist_star_melting_ingot',
    'sakuratinker:materials/two_form_mist_star/two_form_mist_star_material_melt',
    'tinkerscalibration:tools/materials/melting/mangobberslime/mangobberslime',
    'tinkerscalibration:tools/materials/melting/mangobberslime/nugget',
    'tinkerscalibration:tools/materials/melting/mangobberslime/part',
    'tinkers_advanced:materials/anti_neutronium/anti_neutronium_melting_90mb',
    'tinkers_advanced:materials/anti_neutronium/anti_neutronium_material_melting',
    'tinkers_advanced:materials/densium/densium_melting_90mb',
    'tinkers_advanced:materials/densium/densium_material_melting',
    'tinkers_advanced:materials/iridium/iridium_melting_chunk',
    'tinkers_advanced:materials/iridium/iridium_melting_ore',
    'tinkers_advanced:materials/iridium/iridium_material_melt',
    'tinkers_advanced:materials/irradium/irradium_melting_ingot',
    'tinkers_advanced:materials/irradium/irradium_material_melt',
    'tinkers_advanced:materials/protocite/protocite_melting_ingot',
    'tinkers_advanced:materials/protocite/protocite_material_melt',
    'tinkers_advanced:materials/neutronite/neutronite_melting_1mb',
    'tinkers_advanced:materials/activated_chromatic_steel/activated_chromatic_steel_melting_plate',
    'tinkers_advanced:materials/activated_chromatic_steel/activated_chromatic_steel_material_melt',
    'cloudertinker:materials/chimera/melting',
    'cloudertinker:materials/chimera/materials_melting',
    'cloudertinker:materials/magala/evilmare_melting',
    'cloudertinker:materials/magala/evilmare_materials_melting',
    'ticex:smeltery/melting/metal/neutron/block',
    'ticex:smeltery/melting/metal/neutron/ingot',
    'sakuratinker:materials/neutron/neutron_material_melting',
    'ticex:tools/materials/melting/neutron',
    'tprt:materials/tprt/source_alloy/source_alloy',
    'tprt:materials/tprt/source_alloy/source_alloy_material_melting',
    'tprt:materials/tprt/radiant_knightmetal/radiant_knightmetal',
    'tprt:materials/tprt/radiant_knightmetal/radiant_knightmetal_material_melting',
    'tprt:materials/tprt/dark_knight/dark_knight_melting',
    'tprt:materials/tprt/dark_knight/dark_knight_material_melting',
    'momotinker:materials/spirit_visage/spirit_visage_melting',
    'momotinker:materials/spirit_visage/spirit_visage_materials_melting',
    'momotinker:materials/greedy_contract/greedy_contract_melting',
    'momotinker:materials/greedy_contract/greedy_contract_materials_melting',
    'momotinker:materials/lust_mirror/lust_mirror_melting',
    'momotinker:materials/lust_mirror/lust_mirror_materials_melting',
    'momotinker:materials/arrogance_proof/arrogance_proof_melting',
    'momotinker:materials/arrogance_proof/arrogance_proof_materials_melting',
    'momotinker:materials/lazy_grail/lazy_grail_melting',
    'momotinker:materials/lazy_grail/lazy_grail_materials_melting',
    'momotinker:materials/interdimensional_crystal/interdimensional_crystal_melting',
    'momotinker:materials/interdimensional_crystal/interdimensional_crystal_materials_melting',
    'momotinker:materials/dimensional_prism/dimensional_prism_melting',
    'momotinker:materials/dimensional_prism/dimensional_prism_materials_melting',
    'momotinker:materials/dim_dark_gold/dim_dark_gold_melting',
    'momotinker:materials/dim_dark_gold/dim_dark_gold_materials_melting',
    'momotinker:materials/stained_blood_gold/stained_blood_gold_melting',
    'momotinker:materials/stained_blood_gold/stained_blood_gold_materials_melting',
    'momotinker:materials/starry_mysterious_gold/starry_mysterious_gold_melting',
    'momotinker:materials/starry_mysterious_gold/starry_mysterious_gold_materials_melting',
    'momotinker:materials/devouring_demon_gold/devouring_demon_gold_melting',
    'momotinker:materials/devouring_demon_gold/devouring_demon_gold_materials_melting',
    'momotinker:materials/meteor_nucleus/meteor_nucleus_block_melting',
    'momotinker:materials/meteor_nucleus/meteor_nucleus_melting',
    'momotinker:materials/meteor_nucleus/meteor_nucleus_materials_melting',
    'momotinker:materials/ashen_platinum/ashen_platinum_melting',
    'momotinker:materials/ashen_platinum/ashen_platinum_materials_melting',
    'momotinker:materials/hadal_platinum/hadal_platinum_melting',
    'momotinker:materials/hadal_platinum/hadal_platinum_materials_melting',
    'momotinker:materials/stellar_core_platinum/stellar_core_platinum_melting',
    'momotinker:materials/stellar_core_platinum/stellar_core_platinum_materials_melting',
    'momotinker:materials/crystallized_platinum/crystallized_platinum_melting',
    'momotinker:materials/crystallized_platinum/crystallized_platinum_materials_melting',
    'momotinker:materials/living_platinum/living_platinum_melting',
    'momotinker:materials/living_platinum/living_platinum_materials_melting',
    'momotinker:materials/twilight_purple_gold/twilight_purple_gold_melting',
    'momotinker:materials/twilight_purple_gold/twilight_purple_gold_materials_melting',
    'momotinker:materials/timetrace_purple_gold/timetrace_purple_gold_melting',
    'momotinker:materials/timetrace_purple_gold/timetrace_purple_gold_materials_melting',
    'momotinker:materials/reversetime_purple_gold/reversetime_purple_gold_melting',
    'momotinker:materials/reversetime_purple_gold/reversetime_purple_gold_materials_melting',
    'momotinker:materials/rhythm_slime/rhythm_slime_melting',
    'momotinker:materials/rhythm_slime/rhythm_slime_materials_melting',
    'dreamtinker:smeltery/melting/foundry/metallivorous_stibium_lupus/block',
    'dreamtinker:smeltery/melting/foundry/metallivorous_stibium_lupus/ingot',
    'dreamtinker:tools/materials/melting/metallivorous_stibium_lupus',
    'dreamtinker:smeltery/melting/soul_etherium/ingot',
    'dreamtinker:tools/materials/melting/soul_etherium'
], 'stage_4')


RecipeMachineStage.addRecipes('tconstruct:alloying', [
    'mushroom_concept:alloy/molten_almighty',
    'mushroom_concept:alloy/xuan_steel',
    'sakuratinker:materials/gluttonous/gluttonous_alloy',
    'sakuratinker:materials/two_form_mist_star/two_form_mist_star_alloy',
    'tinkers_advanced:materials/densium/densium_material_alloy_1',
    'tinkerscalibration:tools/materials/mangobberslime',
    'tinkers_advanced:materials/activated_chromatic_steel/activated_chromatic_steel_alloy',
    'cloudertinker:alloy/chimera',
    'tconstruct:kjs/evglr7yftc5ywh54y682sdsq6',
    'tprt:materials/tprt/source_alloy/alloy',
    'tprt:materials/tprt/radiant_knightmetal/alloy',
    'dreamtinker:smeltery/alloy/molten_soul_aether'
], 'stage_4')