AStages.addRestrictionForItem("astages/stage2/items/core", "stage_2",
    "avaritia:sculk_crafting_table",
    "aether:zanite_gemstone",
    "alexscaves:tectonic_shard",
    "aquaculture:neptunium_ingot",
    "botania:elementium_ingot",
    "botania:mana_string",
    "botania:manasteel_ingot",
    "cataclysm:black_steel_ingot",
    "cloudertinker:changeheart",
    "cloudertinker:steeleafalloy",
    "cloudertinker:mazeslime_ingot",
    "cloudertinker:sorteye",
    "cloudertinker:minodiamond_gem",
    "cloudertinker:orescore",
    "cloudertinker:timering",
    "cloudertinker:phantom_ingot",
    "cloudertinker:frostiron_ingot",
    "cloudertinker:compositesteeleaf_ingot",
    "mushroom_daydream:copper_green",
    "minecraft:ender_eye",
    "deep_aether:skyjade",
    "mekanism:ingot_refined_glowstone",
    "minecraft:emerald",
    "minecraft:purpur_block",
    "minecraft:prismarine_crystals",
    "minecraft:echo_shard",
    "minecraft:nether_star",
    "mekanism:alloy_atomic",
    "gobber2:gobber2_ingot",
    "sakuratinker:blood_bound_steel",
    "sakuratinker:orichalcum_ingot",
    "mysticalagriculture:prudentium_ingot",
    "mysticalagriculture:tertium_ingot",
    "mushroom_daydream:plague_steel",
    "mushroom_daydream:nightmare_fuel",
    "mushroom_daydream:slime_court_jester",
    "mushroom_daydream:liga",
    "mushroom_daydream:bee_man",
    "tconstruct:silky_cloth",
    "tconstruct:pig_iron_ingot",
    "tconstruct:amethyst_bronze_ingot",
    "tconstruct:nahuatl",
    "tconstruct:necronium_bone",
    "tconstruct:cobalt_ingot",
    "tconstruct:slimesteel_ingot",
    "thermal:invar_ingot",
    "tinkers_thinking:echo_bronze_ingot",
    "tinkers_thinking:chlorophyte_ingot",
    "tinkers_delight:gildedfern",
    "tinkers_delight:mushroom_gold_ingot",
    "tinkers_delight:hot_pot_iron_ingot",
    "tinkers_advanced:nutrition_slime_ingot",
    "tinkers_advanced:basalz_signalum",
    "ticex:draconium_crystal",
    "ticex:wyvern_crystal",
    "tinkers_thinking:chillslime_cryogel",
    "tinkers_thinking:tinkers_bronze_ingot",
    "tinkers_thinking:spectre_ingot",
    "tinkers_thinking:beetron_ingot",
    "tinkers_thinking:electrical_steel_ingot",
    "tinkers_thinking:white_chocolate",
    "tinkers_thinking:shroomite_ingot",
    "tinkers_thinking:lightite_ingot",
    "tinkers_thinking:ancient_ceramic",
    "tinkers_thinking:bacium",
    "tinkers_thinking:ardite_ingot",
    "tinkers_thinking:black_chocolate",
    "tinkers_thinking:obsidian_bronze_ingot",
    "tinkerscalibration:lizanite_crystal",
    "tinkerscalibration:magiga_ingot",
    "tinkerscalibration:corundum",
    "tinkerscalibration:halleium_ingot",
    "tinkerscalibration:spinel",
    "tinkerscalibration:alumite_ingot",
    "tinkerscalibration:tourmaline",
    "tinkerscalibration:fiberglass",
    "tinkerscalibration:hymon",
    "tinkerscalibration:immersed_silver_ingot",
    "tinkerscalibration:steamium_ingot",
    "tinkerscalibration:inert_witherium_ingot",
    "tinkerscalibration:stellarium_ingot",
    "tinkerscalibration:refinedquartz",
    "tinkerscalibration:prehnite_crystal",
    "tinkerscalibration:titanium_ingot",
    "tinkerscalibration:tonium_ingot",
    "twilightforest:alpha_yeti_fur",
    "twilightforest:fiery_ingot",
    "twilightforest:giant_cobblestone",
    "tinkerscalibration:hothium_ingot",
    "twilightforest:carminite",
    "botania:terrasteel_ingot",
    "botania:gaia_ingot"
)

AStages.addRestrictionForTag("astages/stage2/tags/electrum_ingots", "stage_2", "forge:ingots/electrum")
AStages.addRestrictionForTag("astages/stage2/tags/steel_ingots", "stage_2", "forge:ingots/steel")
AStages.addRestrictionForTag("astages/stage2/tags/bronze_ingots", "stage_2", "forge:ingots/bronze")
AStages.addRestrictionForTag("astages/stage2/tags/rose_gold_ingots", "stage_2", "forge:ingots/rose_gold")
AStages.addRestrictionForTag("astages/stage2/tags/constantan_ingots", "stage_2", "forge:ingots/constantan")


AStages.addRestrictionForRecipe("astages/stage2/recipes/sculk_crafting_table", "stage_2", "minecraft:crafting", "avaritia:sculk_crafting_table");

AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/immersiveengineering", "stage_2", "immersiveengineering");
AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/mysticalagradditions", "stage_2", "mysticalagradditions");
AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/mysticalagriculture", "stage_2", "mysticalagriculture");
AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/extrabotany", "stage_2", "extrabotany");
AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/mythicbotany", "stage_2", "mythicbotany");
AStages.addRestrictionForModRecipe("astages/stage2/recipes/mods/botania", "stage_2", "botania");