//置换配方
ServerEvents.recipes(event => {
    //黑钢
    event.shapeless(
        Item.of('wqjy:black_steel_ingot'),
        [
            'cataclysm:black_steel_ingot'
        ]
    )
    event.shapeless(
        Item.of('cataclysm:black_steel_ingot'),
        [
            'wqjy:black_steel_ingot'
        ]
    )
    //凋灵合金
    event.shapeless(
        Item.of('wqjy:witherite_ingot'),
        [
            'cataclysm:witherite_ingot'
        ]
    )
    event.shapeless(
        Item.of('cataclysm:witherite_ingot'),
        [
            'wqjy:witherite_ingot'
        ]
    )
    //咒魂锭
    event.shapeless(
        Item.of('cataclysm:cursium_ingot'),
        [
            'wqjy:cursium_ingot'
        ]
    )
    event.shapeless(
        Item.of('wqjy:cursium_ingot'),
        [
            'cataclysm:cursium_ingot'
        ]
    )
    //腾炎锭
    event.shapeless(
        Item.of('cataclysm:ignitium_ingot'),
        [
            'wqjy:ignitium_ingot'
        ]
    )
    event.shapeless(
        Item.of('wqjy:ignitium_ingot'),
        [
            'cataclysm:ignitium_ingot'
        ]
    )
    //远古金属
    event.shapeless(
        Item.of('wqjy:ancient_metal_ingot'),
        [
            'cataclysm:ancient_metal_ingot'
        ]
    )
    event.shapeless(
        Item.of('cataclysm:ancient_metal_ingot'),
        [
            'wqjy:ancient_metal_ingot'
        ]
    )
});
