# A tool list to disabled tools.
# Support regex. example: minecraft:.*_axe, it match all minecraft axe.
# Default: All Vanilla Tools
tools:
  - minecraft:.*_axe
  - minecraft:.*_hoe
  - minecraft:.*_pickaxe
  - minecraft:.*_shovel
  - minecraft:.*_sword
  - minecraft:.*_helmet
  - minecraft:.*_chestplate
  - minecraft:.*_leggings
  - minecraft:.*_boots
  - ae2:.*_axe
  - ae2:.*_hoe
  - ae2:.*_pickaxe
  - ae2:.*_shovel
  - ae2:.*_sword
  - alexsmobs:transmutation_table
  - alexsmobs:capsid
  - prefab:.*_blade_.*
  - prefab:item_sickle_.*
  - mekanismtools:.*_paxel
  - mekanismtools:.*_axe
  - mekanismtools:.*_pickaxe
  - mekanismtools:.*_sword
  - mekanismtools:.*_shovel
  - mekanismtools:.*_hoe
  - twilightforest:cube_of_.*
  - projecte:dm_shovel
  - projecte:rm_shovel
  - projecte:dm_sword
  - projecte:rm_sword
  - projecte:dm_pick
  - projecte:rm_pick
  - projecte:dm_axe
  - projecte:rm_axe
  - projecte:dm_hammer
  - projecte:rm_hammer
  - projecte:dm_hoe
  - projecte:rm_hoe
  - projecte:dm_shears
  - projecte:rm_shears
  - projecte:dm_helmet
  - projecte:rm_helmet
  - projecte:dm_chestplate
  - projecte:rm_chestplate
  - projecte:dm_leggings
  - projecte:rm_leggings
  - projecte:dm_boots
  - projecte:rm_boots
  - projecte:watch_of_flowing_time
  - immersiveengineering:charging_.*
  - dreamtinker:narcissus_wing

# The text will show on disabled tool's Tooltip
# Support Translation Text
tooltip: tooltip.disable_tools

