
["Limited Damage Indicator Particle"]
	DisplayDamageParticlesEvenWhenDamageIsLow = false
	#Range: > 0
	MaximumNumberOfDamageIndicatorParticle = 100
	#Range: 0.0 ~ 1.7976931348623157E308
	DamageIndicatorParticleMultiplier = 1.0

