type=item
items=firework_star
nbt.display.Name={"italic":false,"extra":[{"text":""},{"color":"red","text":"最"},{"color":"yellow","text":"终"},{"color":"aqua","text":"证"},{"color":"light_purple","text":"明"}],"text":""}
model=item/up