type=item
items=extrabotany:excalibur
nbt.display.Name={"italic":false,"extra":[{"text":""},{"color":"#FF0000","text":"荒"},{"color":"#FF5000","text":"古"},{"color":"#FFA000","text":"岁"},{"color":"#FFFF00","text":"月"},{"color":"#A0FF00","text":"的"},{"color":"#50FF00","text":"永"},{"color":"#00FF00","text":"恒"},{"color":"#00FF50","text":"哀"},{"color":"#00FFA0","text":"歌"}],"text":""}
model=item/wq_2