type=item
items=irons_spellbooks:blood_staff
nbt.display.Name={"italic":false,"extra":[{"text":""},{"color":"#FF0000","text":"繁"},{"color":"#FF5000","text":"花"},{"color":"#FFA000","text":"的"},{"color":"#FFFF00","text":"法"},{"color":"#A0FF00","text":"师"},{"color":"#50FF00","text":"塔"}],"text":""}
model=item/zhang_2